# Generated by Django 3.1.2 on 2020-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='grape',
            name='friendly_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, choices=[('England', 'England'), ('Wales', 'Wales')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.ManyToManyField(to='products.Grape'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('friendly_name',)},
        ),
    ]
