# Generated by Django 3.1.2 on 2020-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201018_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winery',
            options={'verbose_name_plural': 'Wineries'},
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('White', 'White'), ('Sparkling', 'Sparkling'), ('Rosé', 'Rosé'), ('Organic', 'Organic'), ('Vegan-friendly', 'Vegan-friendly')], max_length=254, null=True),
        ),
    ]
