# Generated by Django 3.1.2 on 2020-10-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201021_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('White', 'White'), ('Sparkling', 'Sparkling'), ('Rosé', 'Rosé'), ('Organic', 'Organic'), ('Vegan-friendly', 'Vegan-friendly')], max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Wine_type',
        ),
    ]
