# Generated by Django 3.1.2 on 2020-10-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201021_2245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wine_type',
            unique_together={('name',)},
        ),
    ]
