# Generated by Django 3.1.2 on 2020-10-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201022_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wine_type',
            unique_together=set(),
        ),
    ]
