# Generated by Django 3.1.2 on 2020-10-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201027_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine_type',
            new_name='WineType',
        ),
    ]
